#include "src/utils/functions/mainscreen.pwn"
#include "src/utils/functions/airvehicle.pwn"
#include "src/utils/functions/seavehicle.pwn"
#include "src/utils/functions/silahisim.pwn"
#include "src/utils/functions/randomex.pwn"
#include "src/utils/functions/healthdots.pwn"
#include "src/utils/functions/armordots.pwn"